import { gsap } from 'gsap'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Udon-San (https://sketchfab.com/udonsan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-helmet-785f5cfd848940b1a4a0b8ddeefc9ef1
Title: Sci-Fi Helmet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';

export function Helmet(props) {
  const shapeContainer = useRef(null);
  const { nodes, materials } = useGLTF('Model/sci-fi_helmet (1K).glb');
  useGSAP(() => {
    const tl = gsap.timeline();
    tl.from(shapeContainer.current.position, {
      y: 5,
      duration: 3,
      ease: "circ.out",
    });
    gsap.to(shapeContainer.current.rotation, {
      x: 0,
      y: Math.PI * 2,
      duration: 10,
      ease: "power3.inOut",
    }, "<");
  }, [])

  return (
    <group ref={shapeContainer} {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.726, 260.229, -70.689]} rotation={[-1.62, 0.004, -0.087]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane005_helmet_0.geometry}
            material={materials.helmet}
            rotation={[-0.068, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane008_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane009_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane010_helmet_0.geometry}
            material={materials.helmet}
            rotation={[0.009, -0.122, -0.083]}
            scale={1.152}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane011_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane015_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane014_helmet_0.geometry}
            material={materials.helmet}
            scale={1.032}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane016_helmet_0.geometry}
            material={materials.helmet}
            scale={0.971}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane017_helmet_0.geometry}
            material={materials.helmet}
            scale={0.949}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath001_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cable_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath002_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.NurbsPath003_helmet_0.geometry}
            material={materials.helmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane018_helmet_0.geometry}
            material={materials.helmet}
            position={[0.013, -0.007, 1.361]}
            rotation={[0.303, -0.216, 0.062]}
            scale={0.09}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Model/sci-fi_helmet (1K).glb')